@startuml

ГлобальныйАдминистратор --> (Управление системой)
(Управление системой) -> (Просмотр списка организаций)
(Управление системой) -> (Создание организации)
(Управление системой) -> (Редактирование организации)
(Управление системой) -> (Удаление организации)
(Управление системой) -> (Добавление локального администратора к организации)

(Добавление локального администратора к организации) --> ЛокальныйАдминистратор
ЛокальныйАдминистратор --> (Управление своими мероприятиями)
(Управление своими мероприятиями) -> (Добавление мероприятия)
(Управление своими мероприятиями) -> (Удаление мероприятия)
(Управление своими мероприятиями) -> (Редактирование мероприятия)
(Управление своими мероприятиями) -> (Просмотр отчёта по мероприятию)
(Управление своими мероприятиями) -> (Добавление секретаря к мероприятию)
ЛокальныйАдминистратор --> (Администрирование одного мероприятия)

(Добавление секретаря к мероприятию) --> Секретарь
Секретарь --> (Администрирование одного мероприятия)
(Администрирование одного мероприятия) -> (Добавление события к мероприятию)
(Администрирование одного мероприятия) -> (Удаление события)
(Администрирование одного мероприятия) -> (Редактирование события)
(Администрирование одного мероприятия) -> (Добавление тренеров к мероприятию)
(Добавление тренеров к мероприятию) --> Тренер

НеавторизованныйПользователь --> (Использование возможностей системы без авторизации)
(Использование возможностей системы без авторизации) -> (Изучение материалов по ГТО)
(Использование возможностей системы без авторизации) -> (Использование калькулятора для перевода баллов)
(Использование возможностей системы без авторизации) -> (Проверить результат по id после участия в соревновании)
(Использование возможностей системы без авторизации) -> (Просмотр доступных мероприятий)
(Использование возможностей системы без авторизации) -> (Авторизация)
(Использование возможностей системы без авторизации) -> (Регистрация)

АвторизованныйПользователь --> (Использование возможностей системы после авторизации)
(Использование возможностей системы после авторизации) -> (Подача заявки на участие в мероприятии)

@enduml