@startuml

ЛокальныйАдминистратор -> (Создал мероприятие)
(Создал мероприятие) -> (Назначил секретаря)
(Назначил секретаря) .. Секретарь
(Назначил секретаря) -> (Выбрал таблицу перевода результатов)

@enduml