@startuml


Участник -> (Регистрация в системе)
(Регистрация в системе) -> (Выбор любого мероприятия из доступных)
(Выбор любого мероприятия из доступных) -> (Подаёт заявку на мероприятие)
(Подаёт заявку на мероприятие) <.. (Принять заявку)
(Принять заявку) <- СекретарьЛокальныйАдминистратор
Участник ..> (Принять приглашение)
(Принять приглашение) <.. (Приглашение на участие в мероприятие)
(Приглашение на участие в мероприятие) <- СекретарьЛокальныйАдминистратор

@enduml